"""
Write src/version_generated.h before compilation so BUILD_DATE and GIT_HASH
are available as C string macros.

Must be registered with the 'pre:' prefix in platformio.ini / platformio-examples.ini:

    extra_scripts = pre:extra_scripts/version_gen.py
"""

import os
import subprocess
from datetime import datetime

Import("env")  # noqa: F821  (PlatformIO SCons magic)

# --- git commit hash --------------------------------------------------------
try:
    git_hash = (
        subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL,
        )
        .strip()
        .decode("utf-8")
    )
except Exception:
    git_hash = "unknown"

# --- build date (YYYY-MM-DD) ------------------------------------------------
build_date = datetime.now().strftime("%Y-%m-%d")

# --- write generated header -------------------------------------------------
version_file = os.path.join(env.subst("$PROJECT_SRC_DIR"), "version_generated.h")  # noqa: F821
with open(version_file, "w") as f:
    f.write("// Auto-generated by extra_scripts/version_gen.py — do not edit\n")
    f.write("#pragma once\n")
    f.write(f'#define BUILD_DATE "{build_date}"\n')
    f.write(f'#define GIT_HASH   "{git_hash}"\n')

print(f"[version_gen] BUILD_DATE={build_date}  GIT_HASH={git_hash}")
