"""
Embed web source files in a PROGMEM header before compilation.

Register with PlatformIO using the "pre:" prefix:

    extra_scripts = pre:extra_scripts/web_assets.py
"""

from pathlib import Path

Import("env")  # noqa: F821  (PlatformIO SCons magic)

project_dir = Path(env.subst("$PROJECT_DIR"))  # noqa: F821
asset_file = project_dir / "web" / "index.html"
generated_file = project_dir / "src" / "web_assets.generated.h"
delimiter = "WEB_ASSET"
asset = asset_file.read_text(encoding="utf-8")
asset_size = len(asset.encode("utf-8"))
max_asset_size = 16 * 1024

if f"){delimiter}\"" in asset:
    raise RuntimeError(f"{asset_file} contains the generated raw-string delimiter")
if asset_size > max_asset_size:
    raise RuntimeError(
        f"{asset_file} is {asset_size} bytes; embedded web assets are limited to "
        f"{max_asset_size} bytes to preserve ESP8266 flash headroom"
    )

generated = (
    "// Auto-generated by extra_scripts/web_assets.py from web/index.html; do not edit.\n"
    "#pragma once\n"
    "\n"
    "#include <Arduino.h>\n"
    "\n"
    f"static const char web_index_html[] PROGMEM = R\"{delimiter}(\n"
    f"{asset}"
    f"\n){delimiter}\";\n"
)

if not generated_file.exists() or generated_file.read_text(encoding="utf-8") != generated:
    generated_file.write_text(generated, encoding="utf-8")

print(
    f"[web_assets] embedded {asset_file.relative_to(project_dir)} "
    f"({asset_size}/{max_asset_size} bytes)"
)
