"""
Embed the web interface in a gzipped PROGMEM array before compilation.

Register with PlatformIO using the "pre:" prefix:

    extra_scripts = pre:extra_scripts/web_assets.py

The asset is gzipped rather than minified. Minification would buy roughly
another 10-15% on top of gzip, which does not justify making a firmware build
depend on third-party minifiers; `gzip` is in the standard library. The page is
served with `Content-Encoding: gzip`, which also rules out ESPAsyncWebServer's
`%placeholder%` template processing -- see webpage.cpp.
"""

import gzip
from pathlib import Path

Import("env")  # noqa: F821  (PlatformIO SCons magic)

project_dir = Path(env.subst("$PROJECT_DIR"))  # noqa: F821
asset_file = project_dir / "web" / "index.html"
generated_file = project_dir / "src" / "web_assets.generated.h"

# Budgets the *compressed* size, which is what actually costs flash. The old
# 16 KiB cap protected ESP8266 headroom; ESP32 is the supported target now, so
# the limit is only here to catch an accident, not to shape the interface.
max_compressed_size = 64 * 1024

raw = asset_file.read_bytes()
# mtime=0 so an unchanged asset produces an unchanged header and does not
# trigger a rebuild on every invocation.
compressed = gzip.compress(raw, compresslevel=9, mtime=0)

if len(compressed) > max_compressed_size:
    raise RuntimeError(
        f"{asset_file} compresses to {len(compressed)} bytes; the embedded web "
        f"asset is limited to {max_compressed_size} bytes"
    )

lines = []
for offset in range(0, len(compressed), 16):
    chunk = compressed[offset:offset + 16]
    lines.append("    " + " ".join(f"0x{byte:02x}," for byte in chunk))
body = "\n".join(lines)

generated = (
    "// Auto-generated by extra_scripts/web_assets.py from web/index.html; do not edit.\n"
    "#pragma once\n"
    "\n"
    "#include <Arduino.h>\n"
    "\n"
    "// gzip-compressed; served with Content-Encoding: gzip.\n"
    f"static const unsigned int web_index_html_gz_len = {len(compressed)};\n"
    "static const uint8_t web_index_html_gz[] PROGMEM = {\n"
    f"{body}\n"
    "};\n"
)

if not generated_file.exists() or generated_file.read_text(encoding="utf-8") != generated:
    generated_file.write_text(generated, encoding="utf-8")

print(
    f"[web_assets] embedded {asset_file.relative_to(project_dir)}: "
    f"{len(raw)} raw -> {len(compressed)} gzipped "
    f"({100 * len(compressed) / len(raw):.0f}%) "
    f"of {max_compressed_size} bytes"
)
