#ifndef VERSION_H
#define VERSION_H

#include <Arduino.h>

// Generated by extra_scripts/version_gen.py at build time.
// Falls back to "unknown" if the file doesn't exist yet.
#if __has_include("version_generated.h")
#include "version_generated.h"
#endif

#ifndef BUILD_DATE
#define BUILD_DATE "unknown"
#endif

#ifndef GIT_HASH
#define GIT_HASH "unknown"
#endif

// Returns a version string of the form "YYYY-MM-DD-<commithash>",
// e.g. "2026-05-29-10e5843"
inline String getFirmwareVersion()
{
    return String(BUILD_DATE) + "-" + GIT_HASH;
}

#endif // VERSION_H
